apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-scripts
  namespace: kafka
data:
  test-producer.sh: |
    #!/bin/bash
    kafka-console-producer.sh \
      --broker-list kafka-cluster-kafka-0.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092,kafka-cluster-kafka-1.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092,kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092 \
      --topic test-topic

  test-consumer.sh: |
    #!/bin/bash
    kafka-console-consumer.sh \
      --bootstrap-server kafka-cluster-kafka-0.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092,kafka-cluster-kafka-1.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092,kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092 \
      --topic test-topic \
      --from-beginning

  create-topic.sh: |
    #!/bin/bash
    kafka-topics.sh \
      --create \
      --bootstrap-server kafka-cluster-kafka-0.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092,kafka-cluster-kafka-1.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092,kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092 \
      --topic test-topic \
      --partitions 3 \
      --replication-factor 3 \
      --if-not-exists

  describe-topic.sh: |
    #!/bin/bash
    kafka-topics.sh \
      --describe \
      --bootstrap-server kafka-cluster-kafka-0.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092,kafka-cluster-kafka-1.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092,kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092 \
      --topic test-topic
